package co.edu.unisabana.sigaTutoriass;

public enum ProgramaEnum {
    INGENIERIA_INFORMATICA, INGENIERIA_QUIMICA, INGENIERIA_MECANICA, MEDICINA, FISIOTERAPIA, ENFERMERIA,
    COMUNICACION_SOCIAL, COMUNICACION_AUDIOVISUAL, FILOSOFIA, DERECHO
}
